name: Main

on:
  push:
    tags:
      - "v*.*.*"

env:
  TEX_NAME: paper

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile
        uses: ./latex-action
        with:
          LATEX_FILE_NAME: ${{env.TEX_NAME}}.tex

      - name: Rename
        run: cd src && echo "PDF_NAME=${{env.TEX_NAME}}-${GITHUB_REF:10}" >> $GITHUB_ENV && mv ${{env.TEX_NAME}}.tex ${{env.PDF_NAME}}.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: src/${{env.PDF_NAME}}.pdf
          generate_release_notes: true
